package lt.vu.mif.lab1psk.mybatis.dao;

import lt.vu.mif.lab1psk.mybatis.model.Author;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Sun May 15 15:20:03 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Sun May 15 15:20:03 EEST 2022
     */
    int insert(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Sun May 15 15:20:03 EEST 2022
     */
    Author selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Sun May 15 15:20:03 EEST 2022
     */
    List<Author> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Sun May 15 15:20:03 EEST 2022
     */
    int updateByPrimaryKey(Author record);
}