package lt.vu.mif.lab1psk.mybatis.dao;

import lt.vu.mif.lab1psk.mybatis.model.BookAuthor;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface BookAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK_AUTHOR
     *
     * @mbg.generated Sun May 15 15:20:03 EEST 2022
     */
    int insert(BookAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK_AUTHOR
     *
     * @mbg.generated Sun May 15 15:20:03 EEST 2022
     */
    List<BookAuthor> selectAll();
}