package lt.vu.mif.lab1psk.mybatis.dao;

import lt.vu.mif.lab1psk.mybatis.model.BookAuthor;

import java.util.List;

public interface BookAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK_AUTHOR
     *
     * @mbg.generated Fri Apr 29 20:36:21 EEST 2022
     */
    int insert(BookAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK_AUTHOR
     *
     * @mbg.generated Fri Apr 29 20:36:21 EEST 2022
     */
    List<BookAuthor> selectAll();
}