package lt.vu.mif.lab1psk.mybatis.dao;

import lt.vu.mif.lab1psk.mybatis.model.Publisher;

import java.util.List;

public interface PublisherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Fri Apr 29 20:36:21 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Fri Apr 29 20:36:21 EEST 2022
     */
    int insert(Publisher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Fri Apr 29 20:36:21 EEST 2022
     */
    Publisher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Fri Apr 29 20:36:21 EEST 2022
     */
    List<Publisher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Fri Apr 29 20:36:21 EEST 2022
     */
    int updateByPrimaryKey(Publisher record);
}